"""
=============================================================================
CrystalNet — Dual-Model Training Pipeline
=============================================================================

PURPOSE:
  Train two models that work together to predict crystallization conditions
  from a protein's amino acid sequence.

  Model A: Salt Type Classifier
    - Input:  ESM-2 embedding of protein sequence
    - Output: Which salt to use (NaCl, Ammonium Sulfate, KCl, etc.)

  Model B: Concentration Regressor
    - Input:  ESM-2 embedding + predicted salt type (one-hot encoded)
    - Output: Salt concentration in Molar (M)

INPUT FILE:
  crystallization_dataset.csv  (generated by 01_data_collection.py)
  Columns: pdb_id, sequence, seq_length, salt_concentration_M, salt_type, remark_280

INSTALL:
  pip install torch transformers xgboost scikit-learn matplotlib seaborn pandas numpy joblib

RUN:
  python 03_train_and_evaluate.py

=============================================================================
"""

import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, f1_score, classification_report, confusion_matrix
)
import xgboost as xgb
import joblib
import json
import os
import warnings
warnings.filterwarnings("ignore")

SEED = 42
np.random.seed(SEED)

# Create output directories
os.makedirs("models", exist_ok=True)
os.makedirs("plots_final", exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 1: DATA LOADING & CLEANING
# ─────────────────────────────────────────────────────────────────────────────

def clean_dataset(csv_path="crystallization_dataset.csv", min_salt_count=15):
    print("=" * 60)
    print("SECTION 1: DATA CLEANING")
    print("=" * 60)

    df = pd.read_csv(csv_path)
    print(f"\n  Raw dataset loaded: {len(df)} samples")

    # ── 1a. Remove duplicate sequences ──
    # Same protein appearing multiple times adds no new information
    # and can leak into test set if one copy is in train, another in test
    df = df.drop_duplicates(subset=["sequence"])

    # ── 1b. Remove invalid rows ──
    df = df[df["salt_concentration_M"] > 0]       # no zero/negative
    df = df[df["salt_concentration_M"] <= 4.0]     # nothing above 4M (unrealistic)
    df = df[df["sequence"].str.len() >= 30]        # too-short sequences are fragments
    df = df[df["sequence"].str.len() <= 1500]      # ESM-2 limit is 1022 tokens
    df = df.dropna(subset=["salt_type", "salt_concentration_M", "sequence"])
    
    print(f"  After basic filters: {len(df)}")

    # ── 1c. Standardize salt type names ──
    # REMARK 280 uses inconsistent naming. Map everything to clean display names.
    salt_name_map = {
        "SODIUM CHLORIDE": "Sodium Chloride",
        "NACL": "Sodium Chloride",
        "AMMONIUM SULFATE": "Ammonium Sulfate",
        "AMMONIUM SULPHATE": "Ammonium Sulfate",
        "(NH4)2SO4": "Ammonium Sulfate",
        "POTASSIUM CHLORIDE": "Potassium Chloride",
        "KCL": "Potassium Chloride",
        "MAGNESIUM CHLORIDE": "Magnesium Chloride",
        "MGCL2": "Magnesium Chloride",
        "MGCL": "Magnesium Chloride",
        "LITHIUM SULFATE": "Lithium Sulfate",
        "LITHIUM SULPHATE": "Lithium Sulfate",
        "LI2SO4": "Lithium Sulfate",
        "CALCIUM CHLORIDE": "Calcium Chloride",
        "CACL2": "Calcium Chloride",
        "SODIUM ACETATE": "Sodium Acetate",
        "NAAC": "Sodium Acetate",
        "NA ACETATE": "Sodium Acetate",
        "NAOAC": "Sodium Acetate",
        "SODIUM CITRATE": "Sodium Citrate",
        "SODIUM MALONATE": "Sodium Malonate",
        "SODIUM FORMATE": "Sodium Formate",
        "AMMONIUM CHLORIDE": "Ammonium Chloride",
        "NH4CL": "Ammonium Chloride",
        "SODIUM SULFATE": "Sodium Sulfate",
        "SODIUM SULPHATE": "Sodium Sulfate",
        "NA2SO4": "Sodium Sulfate",
        "ZINC ACETATE": "Zinc Acetate",
        "POTASSIUM PHOSPHATE": "Potassium Phosphate",
        "AMMONIUM ACETATE": "Ammonium Acetate",
    }
    df["salt_display"] = df["salt_type"].map(salt_name_map).fillna(df["salt_type"])

    # ── 1d. Keep only salt types with enough samples ──
    salt_counts = df["salt_display"].value_counts()
    print(f"\n  Salt type distribution:")
    for salt, count in salt_counts.items():
        keep = "KEEP" if count >= min_salt_count else "DROP"

    valid_salts = salt_counts[salt_counts >= min_salt_count].index.tolist()
    df = df[df["salt_display"].isin(valid_salts)].reset_index(drop=True)
    print(f"\n  Kept {len(valid_salts)} salt types, dropped the rest")

    # ── 1e. Remove outliers PER SALT TYPE using IQR method ──
    # Why per-salt? Because NaCl at 0.2M is normal, but Ammonium Sulfate
    # at 0.2M would be an outlier (it's usually 1.5-2.5M).
    cleaned_parts = []
    for salt in valid_salts:
        sub = df[df["salt_display"] == salt].copy()
        Q1 = sub["salt_concentration_M"].quantile(0.25)
        Q3 = sub["salt_concentration_M"].quantile(0.75)
        IQR = Q3 - Q1
        lower = max(0, Q1 - 1.5 * IQR)
        upper = Q3 + 1.5 * IQR
        sub = sub[(sub["salt_concentration_M"] >= lower) &
                  (sub["salt_concentration_M"] <= upper)]
        cleaned_parts.append(sub)

    df = pd.concat(cleaned_parts, ignore_index=True)

    # ── 1f. Log-transform the target ──
    # We use log1p(x) = log(1 + x) instead of log(x) to handle
    # values very close to zero without getting -infinity.
    # At prediction time, we reverse with expm1(y) = exp(y) - 1.

    df["log_salt"] = np.log1p(df["salt_concentration_M"])

    # ── Summary ──
    print(f"\n  CLEANED DATASET: {len(df)} samples, "
          f"{df['salt_display'].nunique()} salt types")
    print(f"  Concentration range: [{df['salt_concentration_M'].min():.4f}, "
          f"{df['salt_concentration_M'].max():.4f}] M")

    return df


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 2: ESM-2 EMBEDDING EXTRACTION
# ─────────────────────────────────────────────────────────────────────────────
#  MODEL CHOICES:
#    esm2_t6_8M_UR50D    → 6 layers,  8M params, 320-dim   (CPU friendly)
#    esm2_t12_35M_UR50D   → 12 layers, 35M params, 480-dim
#    esm2_t33_650M_UR50D  → 33 layers, 650M params, 1280-dim (needs GPU)
# ─────────────────────────────────────────────────────────────────────────────

def extract_esm2_embeddings(sequences, model_name="facebook/esm2_t6_8M_UR50D",
                             batch_size=8, max_length=1022):
    """
    Extract mean-pooled ESM-2 embeddings for a list of protein sequences.
    Returns:
        numpy array of shape (n_sequences, embedding_dim)
        embedding_dim = 320 for t6_8M, 480 for t12_35M, 1280 for t33_650M
    """
    import torch
    from transformers import AutoTokenizer, AutoModel

    print("\n" + "=" * 60)
    print("SECTION 2: ESM-2 EMBEDDING EXTRACTION")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  Model: {model_name}")
    print(f"  Device: {device}")
    print(f"  Sequences: {len(sequences)}")

    # Load tokenizer (converts amino acid letters → integer IDs) and model (the actual neural network)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name).to(device)
    model.eval()  # Set to inference mode — no dropout, no gradient tracking

    all_embeddings = []
    n_batches = (len(sequences) + batch_size - 1) // batch_size

    for i in range(0, len(sequences), batch_size):
        # Truncate sequences longer than ESM-2's limit
        batch = [s[:max_length] for s in sequences[i:i + batch_size]]

        # Tokenize: converts ["MKWV...", "AGYL..."] → tensor of integer IDs
        # padding=True  → shorter sequences in the batch get padded to equal length
        # truncation=True → safety net for anything still too long
        inputs = tokenizer(
            batch,
            return_tensors="pt",    # return PyTorch tensors
            padding=True,
            truncation=True,
            max_length=max_length + 2  # +2 for [CLS] and [EOS] special tokens
        ).to(device)

        # Forward pass through the transformer — no gradients needed
        # (we're not training ESM-2, just using it as a feature extractor)
        with torch.no_grad():
            outputs = model(**inputs)

        # outputs.last_hidden_state shape: (batch_size, seq_length, hidden_dim)
        # This is a vector at EVERY position in the sequence.
        hidden = outputs.last_hidden_state

        # attention_mask tells us which positions are real residues (1)
        # vs padding (0). We need this so padding doesn't affect our average.
        mask = inputs["attention_mask"].unsqueeze(-1)  # shape: (batch, seq, 1)

        # Mean-pool: average hidden states across real residue positions
        # Skip position 0 ([CLS]) and last position ([EOS]) — they're special tokens
        h = hidden[:, 1:-1, :] * mask[:, 1:-1, :]     # zero out padding positions
        lengths = mask[:, 1:-1, :].sum(dim=1).clamp(min=1)  # count real positions
        mean_embedding = (h.sum(dim=1) / lengths)      # average

        all_embeddings.append(mean_embedding.cpu().numpy())

        if (i // batch_size) % 75 == 0:
            print(f"    Batch {i // batch_size + 1}/{n_batches}")

    embeddings = np.vstack(all_embeddings)
    print(f"  Embedding matrix shape: {embeddings.shape}")
    print(f"  (Each protein → {embeddings.shape[1]}-dimensional vector)")

    return embeddings


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 3: HAND-CRAFTED FEATURES (for comparison)
# ─────────────────────────────────────────────────────────────────────────────
#
#  These are traditional physicochemical descriptors computed directly from
#  the amino acid sequence. They capture COMPOSITION but not ORDER.
# ─────────────────────────────────────────────────────────────────────────────

STANDARD_AAS = list("ACDEFGHIKLMNPQRSTVWY")
HYDRO = {
    'A': 1.8, 'R': -4.5, 'N': -3.5, 'D': -3.5, 'C': 2.5,
    'Q': -3.5, 'E': -3.5, 'G': -0.4, 'H': -3.2, 'I': 4.5,
    'L': 3.8, 'K': -3.9, 'M': 1.9, 'F': 2.8, 'P': -1.6,
    'S': -0.8, 'T': -0.7, 'W': -0.9, 'Y': -1.3, 'V': 4.2
}


def extract_handcrafted(sequences):
    """
    Extract physicochemical features from protein sequences.

    Features per sequence (29 total):
      - 20 amino acid composition fractions (how much of each AA)
      - seq_length
      - GRAVY (hydrophobicity average)
      - charge_density (fraction of charged residues D, E, K, R, H)
      - hydrophobic_frac (fraction of hydrophobic residues)
      - polar_frac (fraction of polar residues S, T, N, Q)
      - aromatic_frac (fraction of aromatic residues F, W, Y)
      - tiny_frac (fraction of tiny residues A, G, S)
      - cys_frac (cysteine fraction — relevant for disulfide bonds)
      - pro_frac (proline fraction — relevant for structure rigidity)
    """
    print("\n  Extracting hand-crafted features...")
    features = []
    for seq in sequences:
        counts = Counter(seq)
        n = len(seq)
        f = {}
        for aa in STANDARD_AAS:
            f[f"aa_{aa}"] = counts.get(aa, 0) / n
        f["seq_length"] = n
        f["gravy"] = np.mean([HYDRO.get(aa, 0) for aa in seq])
        f["charge_density"] = sum(1 for aa in seq if aa in "DEKRH") / n
        f["hydrophobic_frac"] = sum(1 for aa in seq if aa in "AVILMFYW") / n
        f["polar_frac"] = sum(1 for aa in seq if aa in "STNQ") / n
        f["aromatic_frac"] = sum(1 for aa in seq if aa in "FWY") / n
        f["tiny_frac"] = sum(1 for aa in seq if aa in "AGS") / n
        f["cys_frac"] = counts.get("C", 0) / n
        f["pro_frac"] = counts.get("P", 0) / n
        features.append(f)

    X = pd.DataFrame(features).values.astype(np.float32)
    names = list(features[0].keys())
    print(f"  Hand-crafted feature matrix: {X.shape} ({len(names)} features)")
    return X, names


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 4: MODEL A — SALT TYPE CLASSIFIER
# ─────────────────────────────────────────────────────────────────────────────
#
#  This model answers: "Given this protein, which salt should I use?"
#
#  It's a multi-class classification problem:
#    Input:  ESM-2 embedding (320-dim, reduced to ~50 via PCA)
#    Output: one of N salt types (NaCl, Ammonium Sulfate, KCl, etc.)
#
#  WHY PCA BEFORE CLASSIFICATION?
#  With ~1000 samples and 320 features, the model can memorize the training
#  data (overfit). PCA compresses to ~50 principal components, keeping 85-95%
#  of the variance but removing noise dimensions that enable memorization.
#
#  We use XGBoost with multi:softprob objective — this outputs a probability
#  distribution over all salt types, not just the top-1 prediction.
#  So the website can show: "NaCl (72%), Ammonium Sulfate (18%), KCl (10%)"
# ─────────────────────────────────────────────────────────────────────────────

def train_salt_classifier(X, y_enc, le, feature_name="ESM-2"):
    """
    Train multiple salt-type classifiers and compare them.
    """
    print("\n" + "=" * 60)
    print(f"SECTION 4: MODEL A — SALT TYPE CLASSIFIER ({feature_name})")
    print("=" * 60)

    n_classes = len(le.classes_)
    print(f"  Classes ({n_classes}): {list(le.classes_)}")
    print(f"  Samples: {len(y_enc)}")
    print(f"  Input features: {X.shape[1]}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=SEED, stratify=y_enc
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    pca = None
    if X.shape[1] > 80:
        n_comp = min(80, X.shape[1], max(2, len(X_train) // 8))
        pca = PCA(n_components=n_comp, random_state=SEED)
        X_train_p = pca.fit_transform(X_train_s)
        X_test_p = pca.transform(X_test_s)
        var_retained = pca.explained_variance_ratio_.sum()
        print(f"  PCA: {X.shape[1]} → {n_comp} components "
              f"({var_retained:.1%} variance retained)")
    else:
        X_train_p = X_train_s
        X_test_p = X_test_s
        print(f"  PCA: skipped for low-dimensional input ({X.shape[1]} features)")

    sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)

    models = {
        "XGBoost": xgb.XGBClassifier(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.6,
            reg_alpha=0.5,
            reg_lambda=3.0,
            min_child_weight=5,
            objective="multi:softprob",
            num_class=n_classes,
            random_state=SEED,
            n_jobs=-1,
            early_stopping_rounds=20,
            eval_metric="mlogloss",
        ),
        "RandomForest": RandomForestClassifier(
            n_estimators=300,
            max_depth=8,
            min_samples_leaf=5,
            max_features="sqrt",
            class_weight="balanced_subsample",
            random_state=SEED,
            n_jobs=-1,
        ),
    }

    results = {}
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    X_all_p = scaler.transform(X) if pca is None else pca.transform(scaler.transform(X))

    for name, model in models.items():
        print(f"\n  Training {name}...")
        if name == "XGBoost":
            model.fit(X_train_p, y_train,
                      sample_weight=sample_weights,
                      eval_set=[(X_test_p, y_test)])
            cv_model = xgb.XGBClassifier(
                n_estimators=200, max_depth=4, learning_rate=0.05,
                subsample=0.8, colsample_bytree=0.6,
                reg_alpha=0.5, reg_lambda=3.0,
                min_child_weight=5, objective="multi:softprob",
                num_class=n_classes, random_state=SEED, n_jobs=-1
            )
        else:
            model.fit(X_train_p, y_train)
            cv_model = RandomForestClassifier(
                n_estimators=300,
                max_depth=8,
                min_samples_leaf=5,
                max_features="sqrt",
                class_weight="balanced_subsample",
                random_state=SEED,
                n_jobs=-1,
            )

        y_pred = model.predict(X_test_p)
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        cv_accs = cross_val_score(
            cv_model, X_all_p, y_enc, cv=cv, scoring="accuracy"
        )

        results[name] = {
            "model": model,
            "accuracy": acc,
            "f1": f1,
            "cv_accuracy": cv_accs.mean(),
            "cv_std": cv_accs.std(),
            "y_pred": y_pred,
        }
        print(f"    {name}: Test Acc={acc:.3f} | F1={f1:.3f} | CV Acc={cv_accs.mean():.3f} ± {cv_accs.std():.3f}")

    best_name = max(results, key=lambda k: results[k]["cv_accuracy"])
    best = results[best_name]
    print(f"\n  Best classifier: {best_name} (CV Acc={best['cv_accuracy']:.3f})")

    return best["model"], scaler, pca, {
        "feature": feature_name,
        "best_model": best_name,
        "accuracy": best["accuracy"],
        "f1": best["f1"],
        "cv_accuracy": best["cv_accuracy"],
        "cv_std": best["cv_std"],
        "all_models": {
            m: {
                "accuracy": results[m]["accuracy"],
                "f1": results[m]["f1"],
                "cv_accuracy": results[m]["cv_accuracy"]
            }
            for m in results
        }
    }, results


def train_dl_classifier(X, y_enc, le, feature_name="DL Combined"):
    """
    Train a PyTorch MLP classifier on sequence features.

    The DL model uses class weights and early stopping to handle
    the class imbalance that exists in the salt set.
    """
    import torch
    import torch.nn as nn
    from torch.utils.data import DataLoader, TensorDataset

    print("\n" + "=" * 60)
    print(f"SECTION 4b: DEEP LEARNING SALT CLASSIFIER ({feature_name})")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  Device: {device}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=SEED, stratify=y_enc
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.176, random_state=SEED, stratify=y_train
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_val_s = scaler.transform(X_val)
    X_test_s = scaler.transform(X_test)

    class_counts = np.bincount(y_train, minlength=len(le.classes_))
    class_weights = torch.tensor(
        (class_counts.sum() / (class_counts + 1e-9)).astype(np.float32),
        dtype=torch.float32,
        device=device
    )
    class_weights = class_weights / class_weights.sum() * len(class_counts)

    train_dataset = TensorDataset(
        torch.tensor(X_train_s, dtype=torch.float32),
        torch.tensor(y_train, dtype=torch.long)
    )
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    input_dim = X.shape[1]
    hidden_dims = [256, 128, 64]

    class SaltMLP(nn.Module):
        def __init__(self, in_dim, hidden_dims, out_dim):
            super().__init__()
            layers = []
            prev = in_dim
            for h in hidden_dims:
                layers.extend([
                    nn.Linear(prev, h),
                    nn.BatchNorm1d(h),
                    nn.ReLU(inplace=True),
                    nn.Dropout(0.3),
                ])
                prev = h
            layers.append(nn.Linear(prev, out_dim))
            self.net = nn.Sequential(*layers)

        def forward(self, x):
            return self.net(x)

    model = SaltMLP(input_dim, hidden_dims, len(le.classes_)).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=8)
    criterion = nn.CrossEntropyLoss(weight=class_weights)

    X_val_t = torch.tensor(X_val_s, dtype=torch.float32, device=device)
    y_val_t = torch.tensor(y_val, dtype=torch.long, device=device)
    X_test_t = torch.tensor(X_test_s, dtype=torch.float32, device=device)

    best_val_acc = 0.0
    best_state = None
    patience = 20
    patience_count = 0
    history = {"train_loss": [], "val_loss": [], "val_acc": []}

    for epoch in range(1, 201):
        model.train()
        epoch_loss = 0.0
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_loss += loss.item() * xb.size(0)
        train_loss = epoch_loss / len(train_loader.dataset)

        model.eval()
        with torch.no_grad():
            val_logits = model(X_val_t)
            val_loss = criterion(val_logits, y_val_t).item()
            val_preds = val_logits.argmax(dim=1)
            val_acc = (val_preds == y_val_t).float().mean().item()

        scheduler.step(val_acc)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_count = 0
        else:
            patience_count += 1
            if patience_count >= patience:
                print(f"    Early stopping at epoch {epoch}")
                break

        if epoch % 20 == 0 or epoch == 1:
            print(f"    Epoch {epoch:03d} | Train loss {train_loss:.4f} | "
                  f"Val loss {val_loss:.4f} | Val acc {val_acc:.3f}")

    model.load_state_dict(best_state)
    model.eval()

    with torch.no_grad():
        test_logits = model(X_test_t)
        y_test_pred = test_logits.argmax(dim=1).cpu().numpy()

    acc = accuracy_score(y_test, y_test_pred)
    report = classification_report(y_test, y_test_pred, target_names=le.classes_, digits=3)

    print(f"\n  DL Test Accuracy: {acc:.3f}")
    print(report)

    torch.save({
        "model_state_dict": model.state_dict(),
        "scaler": scaler,
        "feature_name": feature_name,
        "classes": le.classes_.tolist(),
    }, f"models/dl_salt_classifier_{feature_name.replace(' ', '_')}.pt")
    print(f"  Saved: models/dl_salt_classifier_{feature_name.replace(' ', '_')}.pt")

    return {
        "feature": feature_name,
        "accuracy": acc,
        "best_val_acc": best_val_acc,
        "report": report,
        "history": history,
        "scaler": scaler,
        "model_state": model.state_dict(),
    }


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 5: MODEL B — CONCENTRATION REGRESSOR
# ─────────────────────────────────────────────────────────────────────────────
#
#  This model answers: "Given this protein and the predicted salt type,
#  what concentration should I use?"
#
#  KEY DESIGN: The input is [ESM-2 embedding | salt type one-hot]
#  concatenated. This means the model KNOWS which salt was predicted
#  by Model A, and can learn different concentration ranges per salt.
#
#  At inference, we reverse with expm1() to get back to Molar.
# ─────────────────────────────────────────────────────────────────────────────

def train_concentration_regressor(X_esm, y_conc, y_log, salt_labels, le):
    """
    Train concentration regressor with salt type as an additional feature.
    """
    print("\n" + "=" * 60)
    print("SECTION 5: MODEL B — CONCENTRATION REGRESSOR")
    print("=" * 60)

    # ── 5a. Create one-hot encoding of salt type ──
    # This turns "Sodium Chloride" → [1, 0, 0, 0, ...]
    # and "Ammonium Sulfate" → [0, 1, 0, 0, ...]
    salt_encoded = le.transform(salt_labels)
    n_classes = len(le.classes_)
    salt_onehot = np.zeros((len(salt_encoded), n_classes))
    salt_onehot[np.arange(len(salt_encoded)), salt_encoded] = 1

    # ── 5b. Concatenate embedding + salt one-hot ──
    # Final feature vector = [320 ESM-2 dims | N salt type dims]
    X_combined = np.hstack([X_esm, salt_onehot])
    print(f"  Feature matrix: {X_combined.shape} "
          f"({X_esm.shape[1]} ESM-2 + {n_classes} salt one-hot)")

    # Training target is log-transformed concentration
    y = y_log

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_combined, y, test_size=0.2, random_state=SEED
    )
    # We also need raw concentrations for the test set (for reporting MAE in M)
    _, y_test_raw = train_test_split(y_conc, test_size=0.2, random_state=SEED)
    _, salt_test = train_test_split(salt_labels, test_size=0.2, random_state=SEED)

    # Standardize
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # PCA
    n_comp = min(60, X_combined.shape[1], len(X_train) // 10)
    pca = PCA(n_components=n_comp, random_state=SEED)
    X_train_p = pca.fit_transform(X_train_s)
    X_test_p = pca.transform(X_test_s)
    print(f"  PCA: {X_combined.shape[1]} → {n_comp} "
          f"({pca.explained_variance_ratio_.sum():.1%} variance)")

    # ── 5c. Train Ridge (linear baseline) ──
    # Ridge regression is a linear model with L2 regularization.
    # It almost never overfits, so it gives us a floor:
    # "If XGBoost can't beat Ridge, XGBoost is just memorizing."
    ridge = Ridge(alpha=10.0)
    ridge.fit(X_train_p, y_train)
    y_pred_ridge_log = ridge.predict(X_test_p)
    y_pred_ridge = np.expm1(y_pred_ridge_log)  # convert back from log scale
    mae_ridge = mean_absolute_error(y_test_raw, y_pred_ridge)
    rmse_ridge = np.sqrt(mean_squared_error(y_test_raw, y_pred_ridge))
    r2_ridge = r2_score(y_test_raw, y_pred_ridge)
    print(f"\n  Ridge:   MAE={mae_ridge:.4f} M | RMSE={rmse_ridge:.4f} M | R²={r2_ridge:.4f}")

    # ── 5d. Train XGBoost (regularized) ──
    xgb_model = xgb.XGBRegressor(
        n_estimators=300,
        max_depth=3,              # shallow trees — less overfitting
        learning_rate=0.03,       # slow learning rate
        subsample=0.7,            # use 70% of data per tree
        colsample_bytree=0.6,
        reg_alpha=1.0,            # strong L1 regularization
        reg_lambda=5.0,           # strong L2 regularization
        min_child_weight=10,      # require more samples per leaf
        gamma=0.5,                # minimum loss reduction to make a split
        random_state=SEED,
        n_jobs=-1,
        early_stopping_rounds=20,
    )
    xgb_model.fit(X_train_p, y_train,
                   eval_set=[(X_test_p, y_test)], verbose=False)
    y_pred_xgb_log = xgb_model.predict(X_test_p)
    y_pred_xgb = np.expm1(y_pred_xgb_log)
    mae_xgb = mean_absolute_error(y_test_raw, y_pred_xgb)
    rmse_xgb = np.sqrt(mean_squared_error(y_test_raw, y_pred_xgb))
    r2_xgb = r2_score(y_test_raw, y_pred_xgb)
    print(f"  XGBoost: MAE={mae_xgb:.4f} M | RMSE={rmse_xgb:.4f} M | R²={r2_xgb:.4f}")

    # ── 5e. Cross-validation on XGBoost ──
    X_all_p = pca.transform(scaler.transform(X_combined))
    cv_scores = cross_val_score(
        xgb.XGBRegressor(
            n_estimators=200, max_depth=3, learning_rate=0.03,
            subsample=0.7, colsample_bytree=0.6,
            reg_alpha=1.0, reg_lambda=5.0, min_child_weight=10,
            gamma=0.5, random_state=SEED, n_jobs=-1
        ),
        X_all_p, y, cv=5, scoring="neg_mean_absolute_error"
    )
    print(f"  XGBoost 5-Fold CV MAE (log scale): "
          f"{-cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    # ── 5f. Pick best model ──
    if mae_xgb <= mae_ridge:
        best_model = xgb_model
        best_name = "XGBoost"
        y_pred_best = y_pred_xgb
        best_metrics = {"mae": mae_xgb, "rmse": rmse_xgb, "r2": r2_xgb}
    else:
        best_model = ridge
        best_name = "Ridge"
        y_pred_best = y_pred_ridge
        best_metrics = {"mae": mae_ridge, "rmse": rmse_ridge, "r2": r2_ridge}

    print(f"\n  Best regressor: {best_name} "
          f"(MAE={best_metrics['mae']:.4f} M)")

    # ── 5g. Per-salt-type MAE ──
    print(f"\n  Per-Salt-Type Performance:")
    per_salt = {}
    for salt in le.classes_:
        mask = salt_test == salt
        if mask.sum() >= 3:
            mae_s = mean_absolute_error(y_test_raw[mask], y_pred_best[mask])
            per_salt[salt] = {"mae": mae_s, "count": int(mask.sum())}
            print(f"    {salt:30s} | MAE: {mae_s:.4f} M | n={mask.sum()}")

    # Plotting is disabled in this run.

    # ── Save model artifacts ──
    joblib.dump(best_model, "models/concentration_regressor.joblib")
    joblib.dump(scaler, "models/regressor_scaler.joblib")
    joblib.dump(pca, "models/regressor_pca.joblib")
    print("  Saved model artifacts to models/")

    return best_model, scaler, pca, best_metrics, per_salt


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 6: COMPARISON PLOTS (Hand-Crafted vs ESM-2)
# ─────────────────────────────────────────────────────────────────────────────
#
#  This generates the "money slide" for your presentation:
#  a side-by-side comparison proving ESM-2 features outperform
#  hand-crafted features.
# ─────────────────────────────────────────────────────────────────────────────

def compare_features(X_hc, X_esm, y_conc, y_log, salt_labels, le):
    """
    Comparison is disabled in this run. This stub is retained for compatibility.
    """
    print("SECTION 6: FEATURE COMPARISON is disabled.")
    return {}


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 7: t-SNE VISUALIZATION
# ─────────────────────────────────────────────────────────────────────────────
#
#  t-SNE projects the 320-dim ESM-2 embeddings into 2D for visualization.
#  If proteins that crystallize with similar salts cluster together in the
#  t-SNE plot, that means ESM-2 embeddings ARE capturing information
#  relevant to crystallization — which validates our entire approach.
#
#  This is a powerful presentation slide.
# ─────────────────────────────────────────────────────────────────────────────

def plot_tsne(X_esm, y_conc, salt_labels):
    """t-SNE visualization is disabled in this run."""
    print("SECTION 7: t-SNE visualization is disabled.")


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 8: DATA DISTRIBUTION PLOT
# ─────────────────────────────────────────────────────────────────────────────

def plot_data_overview(df):
    """Data overview plotting is disabled in this run."""
    print("SECTION 8: Data overview plotting is disabled.")


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 9: SAVE INFERENCE CONFIG
# ─────────────────────────────────────────────────────────────────────────────

def save_config(esm_model_name, le):
    """
    Save a JSON config file listing all the model files and settings.
    When you later build the Streamlit app, it reads this config
    to know which files to load.
    """
    config = {
        "esm_model": esm_model_name,
        "salt_classes": le.classes_.tolist(),
        "max_seq_length": 1022,
        "files": {
            "salt_classifier": "models/salt_classifier.joblib",
            "classifier_scaler": "models/classifier_scaler.joblib",
            "classifier_pca": "models/classifier_pca.joblib",
            "label_encoder": "models/label_encoder.joblib",
            "dl_salt_classifier": "models/dl_salt_classifier_DL_Combined.pt",
            "concentration_regressor": "models/concentration_regressor.joblib",
            "regressor_scaler": "models/regressor_scaler.joblib",
            "regressor_pca": "models/regressor_pca.joblib",
        }
    }
    with open("models/config.json", "w") as f:
        json.dump(config, f, indent=2)
    print("\n  Saved: models/config.json")


# ═════════════════════════════════════════════════════════════════════════════
#  MAIN: RUN EVERYTHING
# ═════════════════════════════════════════════════════════════════════════════

def main():
    ESM_MODEL = "facebook/esm2_t6_8M_UR50D"

    # ── 1. Clean data ──
    df = clean_dataset("crystallization_dataset.csv", min_salt_count=15)

    if len(df) < 50:
        print("\nFATAL: Too few samples after cleaning. "
              "Increase max_search in 01_data_collection.py and re-run.")
        return

    sequences = df["sequence"].tolist()
    y_conc = df["salt_concentration_M"].values
    y_log = df["log_salt"].values
    salt_labels = df["salt_display"].values

    # ── 2. Data overview plot ──
    # plot_data_overview(df)

    # ── 3. Extract ESM-2 embeddings ──
    X_esm = extract_esm2_embeddings(sequences, model_name=ESM_MODEL, batch_size=8)

    # ── 4. Extract hand-crafted features (for comparison) ──
    X_hc, hc_names = extract_handcrafted(sequences)

    # ── 5. Train Model A: Salt Type Classifier ──
    le = LabelEncoder()
    y_enc = le.fit_transform(salt_labels)

    feature_sets = [
        ("Hand-Crafted", X_hc),
        ("ESM-2", X_esm),
        ("Combined", np.hstack([X_esm, X_hc]))
    ]

    classifier_results = {}
    for feature_name, X in feature_sets:
        clf, clf_scaler, clf_pca, metrics, all_results = train_salt_classifier(
            X, y_enc, le, feature_name=feature_name
        )
        classifier_results[feature_name] = {
            "clf": clf,
            "scaler": clf_scaler,
            "pca": clf_pca,
            "metrics": metrics,
            "all_results": all_results,
        }

    best_feature = max(
        classifier_results,
        key=lambda name: classifier_results[name]["metrics"]["cv_accuracy"]
    )
    best_clf_info = classifier_results[best_feature]
    print(f"\nBest overall Model A: {best_feature} features "
          f"(best inner model: {best_clf_info['metrics']['best_model']})")

    joblib.dump(best_clf_info["clf"], "models/salt_classifier.joblib")
    joblib.dump(best_clf_info["scaler"], "models/classifier_scaler.joblib")
    joblib.dump(best_clf_info["pca"], "models/classifier_pca.joblib")
    joblib.dump(le, "models/label_encoder.joblib")
    print("  Saved best salt classifier artifacts to models/")

    # ── 5b. Train DL classifier on combined features ──
    dl_results = train_dl_classifier(np.hstack([X_esm, X_hc]), y_enc, le,
                                     feature_name="DL Combined")

    # ── 6. Train Model B: Concentration Regressor ──
    reg, reg_scaler, reg_pca, reg_metrics, per_salt = \
        train_concentration_regressor(X_esm, y_conc, y_log, salt_labels, le)

    # ── 7. Feature comparison (the money slide) ──
    # feat_results = compare_features(X_hc, X_esm, y_conc, y_log, salt_labels, le)

    # ── 8. t-SNE visualization ──
    # # plot_tsne(X_esm, y_conc, salt_labels)

    # ── 9. Save config ──
    save_config(ESM_MODEL, le)

    # ══════════════════════════════════════════════════════════════════════
    #  FINAL SUMMARY
    # ══════════════════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("TRAINING COMPLETE")
    print("=" * 60)

    print(f"\n  Dataset: {len(df)} samples, {df['salt_display'].nunique()} salt types")

    print(f"\n  MODEL A — Salt Type Classifier Results:")
    for feature_name, info in classifier_results.items():
        print(f"    {feature_name:10s} → Best model: {info['metrics']['best_model']:12s} | "
              f"Test Acc: {info['metrics']['accuracy']:.1%} | "
              f"F1: {info['metrics']['f1']:.1%} | "
              f"CV Acc: {info['metrics']['cv_accuracy']:.1%}")

    print(f"\n  Best overall classifier: {best_feature} features "
          f"({best_clf_info['metrics']['best_model']})")

    print(f"\n  MODEL B — Concentration Regressor:")
    print(f"    MAE:  {reg_metrics['mae']:.4f} M")
    print(f"    RMSE: {reg_metrics['rmse']:.4f} M")
    print(f"    R²:   {reg_metrics['r2']:.4f}")

    print(f"\n  MODEL A — Deep Learning Classifier:")
    print(f"    Feature set: {dl_results['feature']}")
    print(f"    Test Accuracy: {dl_results['accuracy']:.1%}")
    print(f"    Best validation accuracy: {dl_results['best_val_acc']:.1%}")


if __name__ == "__main__":
    main()
