"""
=============================================================================
CrystalNet — Dual-Model Training Pipeline
=============================================================================

PURPOSE:
  Train two models that work together to predict crystallization conditions
  from a protein's amino acid sequence.

  Model A: Salt Type Classifier
    - Input:  ESM-2 embedding of protein sequence
    - Output: Which salt to use (NaCl, Ammonium Sulfate, KCl, etc.)

  Model B: Concentration Regressor
    - Input:  ESM-2 embedding + predicted salt type (one-hot encoded)
    - Output: Salt concentration in Molar (M)

  WHY TWO MODELS?
    Different salts have completely different concentration ranges in
    crystallization experiments:
      NaCl              → typically 0.05 – 0.5 M
      Ammonium Sulfate  → typically 1.0 – 3.0 M
      MgCl₂             → typically 0.01 – 0.2 M

    A single regressor predicting concentration without knowing the
    salt type would be confused by these overlapping ranges. Splitting
    into classification + regression gives each model a cleaner task.

INPUT FILE:
  crystallization_dataset.csv  (generated by 01_data_collection.py)
  Columns: pdb_id, sequence, seq_length, salt_concentration_M, salt_type, remark_280

OUTPUT:
  models/                       — saved model files for deployment
  plots_final/                  — presentation-ready evaluation plots

INSTALL:
  pip install torch transformers xgboost scikit-learn matplotlib seaborn pandas numpy joblib

RUN:
  python 04_dual_model_training.py

=============================================================================
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # non-interactive backend so it works on servers
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from sklearn.model_selection import (
    train_test_split, cross_val_score, StratifiedKFold
)
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    accuracy_score, classification_report, confusion_matrix
)
import xgboost as xgb
try:
    from catboost import CatBoostClassifier
except ImportError:
    CatBoostClassifier = None
import joblib
import json
import os
import warnings
warnings.filterwarnings("ignore")

SEED = 42
np.random.seed(SEED)

# Create output directories
os.makedirs("models", exist_ok=True)
os.makedirs("plots_final", exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 1: DATA LOADING & CLEANING
# ─────────────────────────────────────────────────────────────────────────────
#
#  The raw dataset from Stage 1 has issues:
#    - Multiple salt types mixed together (NaCl, Ammonium Sulfate, etc.)
#    - Salt types with very few samples (can't train a classifier on 3 samples)
#    - Outlier concentrations from parsing errors in REMARK 280
#    - Duplicate sequences
#
#  This section cleans all of that.
# ─────────────────────────────────────────────────────────────────────────────

def clean_dataset(csv_path="crystallization_dataset.csv", min_salt_count=15):
    """
    Load raw dataset and apply cleaning steps.

    Args:
        csv_path:        Path to the CSV from Stage 1
        min_salt_count:  Minimum samples a salt type must have to be kept.
                         Salt types with fewer samples are dropped because
                         the classifier can't learn from too few examples.

    Returns:
        df:  Cleaned pandas DataFrame with columns:
             pdb_id, sequence, salt_concentration_M, salt_type,
             salt_display (clean name), log_salt (log-transformed target)
    """
    print("=" * 60)
    print("SECTION 1: DATA CLEANING")
    print("=" * 60)

    df = pd.read_csv(csv_path)
    print(f"\n  Raw dataset loaded: {len(df)} samples")

    # ── 1a. Remove duplicate sequences ──
    # Same protein appearing multiple times adds no new information
    # and can leak into test set if one copy is in train, another in test
    df = df.drop_duplicates(subset=["sequence"])
    print(f"  After removing duplicate sequences: {len(df)}")

    # ── 1b. Remove invalid rows ──
    df = df[df["salt_concentration_M"] > 0]       # no zero/negative
    df = df[df["salt_concentration_M"] <= 4.0]     # nothing above 4M (unrealistic)
    df = df[df["sequence"].str.len() >= 30]        # too-short sequences are fragments
    df = df[df["sequence"].str.len() <= 1500]      # ESM-2 limit is 1022 tokens
    df = df.dropna(subset=["salt_type", "salt_concentration_M", "sequence"])
    
    print(f"  After basic filters: {len(df)}")

    # ── 1c. Standardize salt type names ──
    # REMARK 280 uses inconsistent naming. Map everything to clean display names.
    salt_name_map = {
        "SODIUM CHLORIDE": "Sodium Chloride",
        "NACL": "Sodium Chloride",
        "AMMONIUM SULFATE": "Ammonium Sulfate",
        "AMMONIUM SULPHATE": "Ammonium Sulfate",
        "(NH4)2SO4": "Ammonium Sulfate",
        "POTASSIUM CHLORIDE": "Potassium Chloride",
        "KCL": "Potassium Chloride",
        "MAGNESIUM CHLORIDE": "Magnesium Chloride",
        "MGCL2": "Magnesium Chloride",
        "MGCL": "Magnesium Chloride",
        "LITHIUM SULFATE": "Lithium Sulfate",
        "LITHIUM SULPHATE": "Lithium Sulfate",
        "LI2SO4": "Lithium Sulfate",
        "CALCIUM CHLORIDE": "Calcium Chloride",
        "CACL2": "Calcium Chloride",
        "SODIUM ACETATE": "Sodium Acetate",
        "NAAC": "Sodium Acetate",
        "NA ACETATE": "Sodium Acetate",
        "NAOAC": "Sodium Acetate",
        "SODIUM CITRATE": "Sodium Citrate",
        "SODIUM MALONATE": "Sodium Malonate",
        "SODIUM FORMATE": "Sodium Formate",
        "AMMONIUM CHLORIDE": "Ammonium Chloride",
        "NH4CL": "Ammonium Chloride",
        "SODIUM SULFATE": "Sodium Sulfate",
        "SODIUM SULPHATE": "Sodium Sulfate",
        "NA2SO4": "Sodium Sulfate",
        "ZINC ACETATE": "Zinc Acetate",
        "POTASSIUM PHOSPHATE": "Potassium Phosphate",
        "AMMONIUM ACETATE": "Ammonium Acetate",
    }
    df["salt_display"] = df["salt_type"].map(salt_name_map).fillna(df["salt_type"])

    # ── 1d. Keep only salt types with enough samples ──
    salt_counts = df["salt_display"].value_counts()
    print(f"\n  Salt type distribution:")
    for salt, count in salt_counts.items():
        keep = "KEEP" if count >= min_salt_count else "DROP"
        print(f"    [{keep}] {salt}: {count} samples")

    valid_salts = salt_counts[salt_counts >= min_salt_count].index.tolist()
    df = df[df["salt_display"].isin(valid_salts)].reset_index(drop=True)
    print(f"\n  Kept {len(valid_salts)} salt types, dropped the rest")

    # ── 1e. Remove outliers PER SALT TYPE using IQR method ──
    # Why per-salt? Because NaCl at 0.2M is normal, but Ammonium Sulfate
    # at 0.2M would be an outlier (it's usually 1.5-2.5M).
    cleaned_parts = []
    for salt in valid_salts:
        sub = df[df["salt_display"] == salt].copy()
        Q1 = sub["salt_concentration_M"].quantile(0.25)
        Q3 = sub["salt_concentration_M"].quantile(0.75)
        IQR = Q3 - Q1
        lower = max(0, Q1 - 1.5 * IQR)
        upper = Q3 + 1.5 * IQR
        before = len(sub)
        sub = sub[(sub["salt_concentration_M"] >= lower) &
                  (sub["salt_concentration_M"] <= upper)]
        print(f"    {salt}: {before} → {len(sub)} after IQR filter "
              f"[{lower:.3f}, {upper:.3f}] M")
        cleaned_parts.append(sub)

    df = pd.concat(cleaned_parts, ignore_index=True)

    # ── 1f. Log-transform the target ──
    # Salt concentrations are log-normally distributed (most are small,
    # a few are large). Log transform makes the distribution more symmetric,
    # which is easier for regression models to learn.
    #
    # We use log1p(x) = log(1 + x) instead of log(x) to handle
    # values very close to zero without getting -infinity.
    #
    # At prediction time, we reverse with expm1(y) = exp(y) - 1.
    df["log_salt"] = np.log1p(df["salt_concentration_M"])

    # ── Summary ──
    print(f"\n  CLEANED DATASET: {len(df)} samples, "
          f"{df['salt_display'].nunique()} salt types")
    print(f"  Concentration range: [{df['salt_concentration_M'].min():.4f}, "
          f"{df['salt_concentration_M'].max():.4f}] M")

    return df


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 2: ESM-2 EMBEDDING EXTRACTION
# ─────────────────────────────────────────────────────────────────────────────
#
#  WHY ESM-2?
#  Hand-crafted features (AA composition, GRAVY, charge, etc.) treat the
#  protein as a "bag of amino acids" — they throw away sequence ORDER.
#  Two sequences with identical composition but different order fold
#  differently and crystallize differently.
#
#  ESM-2 is a transformer trained on 250M+ protein sequences via masked
#  language modeling (like BERT for proteins). Its embeddings capture:
#    - Evolutionary conservation at each position
#    - Predicted secondary/tertiary structure
#    - Functional motifs and binding sites
#    - Contextual relationships between distant residues
#
#  WHY MEAN-POOLING INSTEAD OF [CLS] TOKEN?
#  ESM-2 was trained with masked language modeling, NOT with a [CLS]
#  classification objective like BERT. So the [CLS] token doesn't have
#  a dedicated training signal and isn't guaranteed to be a good
#  whole-sequence summary. Mean-pooling across all residue positions
#  aggregates information from every part of the sequence and empirically
#  works better.
#
#  MODEL CHOICES:
#    esm2_t6_8M_UR50D    → 6 layers,  8M params, 320-dim   (CPU friendly)
#    esm2_t12_35M_UR50D   → 12 layers, 35M params, 480-dim
#    esm2_t33_650M_UR50D  → 33 layers, 650M params, 1280-dim (needs GPU)
#
#  For a BTP project on CPU, t6_8M is the sweet spot.
# ─────────────────────────────────────────────────────────────────────────────

def extract_esm2_embeddings(sequences, model_name="facebook/esm2_t6_8M_UR50D",
                             batch_size=8, max_length=1022):
    """
    Extract mean-pooled ESM-2 embeddings for a list of protein sequences.

    How it works:
      1. Tokenize each sequence (each amino acid → integer token ID)
      2. Pass tokens through ESM-2 transformer → hidden states at each position
      3. Average (mean-pool) hidden states across all residue positions
         (skipping the special [CLS] and [EOS] tokens at positions 0 and -1)
      4. The result is a fixed-size vector regardless of sequence length

    Args:
        sequences:    List of protein sequence strings
        model_name:   HuggingFace model identifier
        batch_size:   How many sequences to process at once
        max_length:   Maximum sequence length (ESM-2 limit = 1022 residues)

    Returns:
        numpy array of shape (n_sequences, embedding_dim)
        embedding_dim = 320 for t6_8M, 480 for t12_35M, 1280 for t33_650M
    """
    import torch
    from transformers import AutoTokenizer, AutoModel

    print("\n" + "=" * 60)
    print("SECTION 2: ESM-2 EMBEDDING EXTRACTION")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  Model: {model_name}")
    print(f"  Device: {device}")
    print(f"  Sequences: {len(sequences)}")

    # Load tokenizer (converts amino acid letters → integer IDs)
    # and model (the actual neural network)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name).to(device)
    model.eval()  # Set to inference mode — no dropout, no gradient tracking

    all_embeddings = []
    n_batches = (len(sequences) + batch_size - 1) // batch_size

    for i in range(0, len(sequences), batch_size):
        # Truncate sequences longer than ESM-2's limit
        batch = [s[:max_length] for s in sequences[i:i + batch_size]]

        # Tokenize: converts ["MKWV...", "AGYL..."] → tensor of integer IDs
        # padding=True  → shorter sequences in the batch get padded to equal length
        # truncation=True → safety net for anything still too long
        inputs = tokenizer(
            batch,
            return_tensors="pt",    # return PyTorch tensors
            padding=True,
            truncation=True,
            max_length=max_length + 2  # +2 for [CLS] and [EOS] special tokens
        ).to(device)

        # Forward pass through the transformer — no gradients needed
        # (we're not training ESM-2, just using it as a feature extractor)
        with torch.no_grad():
            outputs = model(**inputs)

        # outputs.last_hidden_state shape: (batch_size, seq_length, hidden_dim)
        # This is a vector at EVERY position in the sequence.
        hidden = outputs.last_hidden_state

        # attention_mask tells us which positions are real residues (1)
        # vs padding (0). We need this so padding doesn't affect our average.
        mask = inputs["attention_mask"].unsqueeze(-1)  # shape: (batch, seq, 1)

        # Mean-pool: average hidden states across real residue positions
        # Skip position 0 ([CLS]) and last position ([EOS]) — they're special tokens
        h = hidden[:, 1:-1, :] * mask[:, 1:-1, :]     # zero out padding positions
        lengths = mask[:, 1:-1, :].sum(dim=1).clamp(min=1)  # count real positions
        mean_embedding = (h.sum(dim=1) / lengths)      # average

        all_embeddings.append(mean_embedding.cpu().numpy())

        if (i // batch_size) % 25 == 0:
            print(f"    Batch {i // batch_size + 1}/{n_batches}")

    embeddings = np.vstack(all_embeddings)
    print(f"  Embedding matrix shape: {embeddings.shape}")
    print(f"  (Each protein → {embeddings.shape[1]}-dimensional vector)")

    return embeddings


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 3: HAND-CRAFTED FEATURES (for comparison)
# ─────────────────────────────────────────────────────────────────────────────
#
#  These are traditional physicochemical descriptors computed directly from
#  the amino acid sequence. They capture COMPOSITION but not ORDER.
#
#  We include them so we can compare:
#    "Does ESM-2 actually help, or do simple features work just as well?"
#  This comparison is a key slide in your presentation.
# ─────────────────────────────────────────────────────────────────────────────

STANDARD_AAS = list("ACDEFGHIKLMNPQRSTVWY")
HYDRO = {
    'A': 1.8, 'R': -4.5, 'N': -3.5, 'D': -3.5, 'C': 2.5,
    'Q': -3.5, 'E': -3.5, 'G': -0.4, 'H': -3.2, 'I': 4.5,
    'L': 3.8, 'K': -3.9, 'M': 1.9, 'F': 2.8, 'P': -1.6,
    'S': -0.8, 'T': -0.7, 'W': -0.9, 'Y': -1.3, 'V': 4.2
}


def extract_handcrafted(sequences):
    """
    Extract physicochemical features from protein sequences.

    Features per sequence (29 total):
      - 20 amino acid composition fractions (how much of each AA)
      - seq_length
      - GRAVY (hydrophobicity average)
      - charge_density (fraction of charged residues D, E, K, R, H)
      - hydrophobic_frac (fraction of hydrophobic residues)
      - polar_frac (fraction of polar residues S, T, N, Q)
      - aromatic_frac (fraction of aromatic residues F, W, Y)
      - tiny_frac (fraction of tiny residues A, G, S)
      - cys_frac (cysteine fraction — relevant for disulfide bonds)
      - pro_frac (proline fraction — relevant for structure rigidity)
    """
    print("\n  Extracting hand-crafted features...")
    features = []
    for seq in sequences:
        counts = Counter(seq)
        n = len(seq)
        f = {}
        for aa in STANDARD_AAS:
            f[f"aa_{aa}"] = counts.get(aa, 0) / n
        f["seq_length"] = n
        f["gravy"] = np.mean([HYDRO.get(aa, 0) for aa in seq])
        f["charge_density"] = sum(1 for aa in seq if aa in "DEKRH") / n
        f["hydrophobic_frac"] = sum(1 for aa in seq if aa in "AVILMFYW") / n
        f["polar_frac"] = sum(1 for aa in seq if aa in "STNQ") / n
        f["aromatic_frac"] = sum(1 for aa in seq if aa in "FWY") / n
        f["tiny_frac"] = sum(1 for aa in seq if aa in "AGS") / n
        f["cys_frac"] = counts.get("C", 0) / n
        f["pro_frac"] = counts.get("P", 0) / n
        features.append(f)

    X = pd.DataFrame(features).values.astype(np.float32)
    names = list(features[0].keys())
    print(f"  Hand-crafted feature matrix: {X.shape} ({len(names)} features)")
    return X, names


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 4: MODEL A — SALT TYPE CLASSIFIER
# ─────────────────────────────────────────────────────────────────────────────
#
#  This model answers: "Given this protein, which salt should I use?"
#
#  It's a multi-class classification problem:
#    Input:  ESM-2 embedding (320-dim, reduced to ~50 via PCA)
#    Output: one of N salt types (NaCl, Ammonium Sulfate, KCl, etc.)
#
#  WHY PCA BEFORE CLASSIFICATION?
#  With ~1000 samples and 320 features, the model can memorize the training
#  data (overfit). PCA compresses to ~50 principal components, keeping 85-95%
#  of the variance but removing noise dimensions that enable memorization.
#
#  We use XGBoost with multi:softprob objective — this outputs a probability
#  distribution over all salt types, not just the top-1 prediction.
#  So the website can show: "NaCl (72%), Ammonium Sulfate (18%), KCl (10%)"
# ─────────────────────────────────────────────────────────────────────────────

def train_salt_classifier(X, y_enc, le, feature_name="ESM-2"):
    """
    Train multiple salt-type classifiers and compare them.

    Args:
        X:            Feature matrix for classification
        y_enc:        Integer-encoded salt labels
        le:           LabelEncoder fitted on salt labels
        feature_name: Name of the feature set for prints/plots

    Returns:
        best_clf:      The best classifier chosen by CV accuracy
        scaler:        StandardScaler fitted on training data
        pca:           PCA transformer fitted on training data (or None)
        metrics:       Dict with per-model results and best model result
        result_table:  Dict containing all model metrics for comparison
    """
    print("\n" + "=" * 60)
    print(f"SECTION 4: MODEL A — SALT TYPE CLASSIFIER ({feature_name})")
    print("=" * 60)

    n_classes = len(le.classes_)
    print(f"  Classes ({n_classes}): {list(le.classes_)}")
    print(f"  Samples: {len(y_enc)}")
    print(f"  Input features: {X.shape[1]}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=SEED, stratify=y_enc
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    pca = None
    if X.shape[1] > 80:
        n_comp = min(80, X.shape[1], max(2, len(X_train) // 8))
        pca = PCA(n_components=n_comp, random_state=SEED)
        X_train_p = pca.fit_transform(X_train_s)
        X_test_p = pca.transform(X_test_s)
        var_retained = pca.explained_variance_ratio_.sum()
        print(f"  PCA: {X.shape[1]} → {n_comp} components "
              f"({var_retained:.1%} variance retained)")
    else:
        X_train_p = X_train_s
        X_test_p = X_test_s
        print(f"  PCA: skipped for low-dimensional input ({X.shape[1]} features)")

    sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)

    models = {
        "XGBoost": xgb.XGBClassifier(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.6,
            reg_alpha=0.5,
            reg_lambda=3.0,
            min_child_weight=5,
            objective="multi:softprob",
            num_class=n_classes,
            random_state=SEED,
            n_jobs=-1,
            early_stopping_rounds=20,
            eval_metric="mlogloss",
        ),
        "CatBoost": CatBoostClassifier(
            iterations=300,
            depth=6,
            learning_rate=0.05,
            l2_leaf_reg=3.0,
            loss_function="MultiClass",
            random_seed=SEED,
            verbose=False,
            task_type="CPU",
        ) if CatBoostClassifier is not None else None,
        "RandomForest": RandomForestClassifier(
            n_estimators=300,
            max_depth=8,
            min_samples_leaf=5,
            max_features="sqrt",
            class_weight="balanced_subsample",
            random_state=SEED,
            n_jobs=-1,
        ),
    }

    results = {}
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    X_all_p = scaler.transform(X) if pca is None else pca.transform(scaler.transform(X))

    for name, model in models.items():
        if model is None:
            print(f"\n  Skipping {name}: CatBoost is not installed.")
            continue
        print(f"\n  Training {name}...")
        if name == "XGBoost":
            model.fit(X_train_p, y_train,
                      sample_weight=sample_weights,
                      eval_set=[(X_test_p, y_test)])
            cv_model = xgb.XGBClassifier(
                n_estimators=200, max_depth=4, learning_rate=0.05,
                subsample=0.8, colsample_bytree=0.6,
                reg_alpha=0.5, reg_lambda=3.0,
                min_child_weight=5, objective="multi:softprob",
                num_class=n_classes, random_state=SEED, n_jobs=-1
            )
        elif name == "CatBoost":
            class_weights = [float(w) for w in (len(y_train) / (np.bincount(y_train) + 1e-9))]
            model.set_params(class_weights=class_weights)
            model.fit(X_train_p, y_train,
                      eval_set=(X_test_p, y_test),
                      use_best_model=True)
            cv_model = CatBoostClassifier(
                iterations=200,
                depth=6,
                learning_rate=0.05,
                l2_leaf_reg=3.0,
                loss_function="MultiClass",
                random_seed=SEED,
                verbose=False,
                task_type="CPU",
                class_weights=class_weights,
            )
        else:
            model.fit(X_train_p, y_train)
            cv_model = RandomForestClassifier(
                n_estimators=300,
                max_depth=8,
                min_samples_leaf=5,
                max_features="sqrt",
                class_weight="balanced_subsample",
                random_state=SEED,
                n_jobs=-1,
            )

        y_pred = model.predict(X_test_p)
        acc = accuracy_score(y_test, y_pred)
        cv_accs = cross_val_score(
            cv_model, X_all_p, y_enc, cv=cv, scoring="accuracy"
        )

        results[name] = {
            "model": model,
            "accuracy": acc,
            "cv_accuracy": cv_accs.mean(),
            "cv_std": cv_accs.std(),
            "y_pred": y_pred,
        }
        print(f"    {name}: Test Acc={acc:.3f} | CV Acc={cv_accs.mean():.3f} ± {cv_accs.std():.3f}")

    best_name = max(results, key=lambda k: results[k]["cv_accuracy"])
    best = results[best_name]
    print(f"\n  Best classifier: {best_name} (CV Acc={best['cv_accuracy']:.3f})")

    cm = confusion_matrix(y_test, best["y_pred"])
    fig, ax = plt.subplots(figsize=(max(8, n_classes * 1.2), max(6, n_classes)))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=le.classes_, yticklabels=le.classes_, ax=ax)
    ax.set_xlabel("Predicted Salt Type", fontsize=11)
    ax.set_ylabel("Actual Salt Type", fontsize=11)
    ax.set_title(f"Model A: Salt Type Classifier ({feature_name})\n"
                 f"{best_name} | Test Acc: {best['accuracy']:.1%} | "
                 f"CV Acc: {best['cv_accuracy']:.1%}",
                 fontsize=13, fontweight="bold")
    plt.xticks(rotation=30, ha="right", fontsize=9)
    plt.yticks(rotation=0, fontsize=9)
    plt.tight_layout()
    plt.savefig(f"plots_final/01_salt_classifier_confusion_{feature_name.replace(' ', '_')}.png",
                dpi=200, bbox_inches="tight")
    plt.close()
    print(f"  Saved: plots_final/01_salt_classifier_confusion_{feature_name.replace(' ', '_')}.png")

    per_class_acc = cm.diagonal() / cm.sum(axis=1)
    fig, ax = plt.subplots(figsize=(10, max(4, n_classes * 0.6)))
    colors = ["#2E86AB" if a >= 0.5 else "#E84855" for a in per_class_acc]
    bars = ax.barh(le.classes_, per_class_acc, color=colors,
                   edgecolor="white", height=0.6)
    ax.axvline(0.5, color="gray", linestyle="--", alpha=0.5, label="50% baseline")
    ax.set_xlabel("Accuracy", fontsize=12)
    ax.set_title(f"Per-Salt-Type Accuracy ({feature_name})", fontsize=13,
                 fontweight="bold")
    for bar, val in zip(bars, per_class_acc):
        ax.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height() / 2,
                f"{val:.1%}", va="center", fontsize=10)
    ax.legend()
    plt.tight_layout()
    plt.savefig(f"plots_final/02_per_class_accuracy_{feature_name.replace(' ', '_')}.png",
                dpi=200, bbox_inches="tight")
    plt.close()
    print(f"  Saved: plots_final/02_per_class_accuracy_{feature_name.replace(' ', '_')}.png")

    return best["model"], scaler, pca, {
        "feature": feature_name,
        "best_model": best_name,
        "accuracy": best["accuracy"],
        "cv_accuracy": best["cv_accuracy"],
        "cv_std": best["cv_std"],
        "all_models": {
            m: {"accuracy": results[m]["accuracy"], "cv_accuracy": results[m]["cv_accuracy"]}
            for m in results
        }
    }, results


def train_dl_classifier(X, y_enc, le, feature_name="DL Combined"):
    """
    Train a PyTorch MLP classifier on sequence features.

    The DL model uses class weights and early stopping to handle
    the class imbalance that exists in the salt set.
    """
    import torch
    import torch.nn as nn
    from torch.utils.data import DataLoader, TensorDataset

    print("\n" + "=" * 60)
    print(f"SECTION 4b: DEEP LEARNING SALT CLASSIFIER ({feature_name})")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  Device: {device}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_enc, test_size=0.2, random_state=SEED, stratify=y_enc
    )
    X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.176, random_state=SEED, stratify=y_train
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_val_s = scaler.transform(X_val)
    X_test_s = scaler.transform(X_test)

    class_counts = np.bincount(y_train, minlength=len(le.classes_))
    class_weights = torch.tensor(
        (class_counts.sum() / (class_counts + 1e-9)).astype(np.float32),
        dtype=torch.float32,
        device=device
    )
    class_weights = class_weights / class_weights.sum() * len(class_counts)

    train_dataset = TensorDataset(
        torch.tensor(X_train_s, dtype=torch.float32),
        torch.tensor(y_train, dtype=torch.long)
    )
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    input_dim = X.shape[1]
    hidden_dims = [256, 128, 64]

    class SaltMLP(nn.Module):
        def __init__(self, in_dim, hidden_dims, out_dim):
            super().__init__()
            layers = []
            prev = in_dim
            for h in hidden_dims:
                layers.extend([
                    nn.Linear(prev, h),
                    nn.BatchNorm1d(h),
                    nn.ReLU(inplace=True),
                    nn.Dropout(0.3),
                ])
                prev = h
            layers.append(nn.Linear(prev, out_dim))
            self.net = nn.Sequential(*layers)

        def forward(self, x):
            return self.net(x)

    model = SaltMLP(input_dim, hidden_dims, len(le.classes_)).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-3)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=8)
    criterion = nn.CrossEntropyLoss(weight=class_weights)

    X_val_t = torch.tensor(X_val_s, dtype=torch.float32, device=device)
    y_val_t = torch.tensor(y_val, dtype=torch.long, device=device)
    X_test_t = torch.tensor(X_test_s, dtype=torch.float32, device=device)

    best_val_acc = 0.0
    best_state = None
    patience = 20
    patience_count = 0
    history = {"train_loss": [], "val_loss": [], "val_acc": []}

    for epoch in range(1, 201):
        model.train()
        epoch_loss = 0.0
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            epoch_loss += loss.item() * xb.size(0)
        train_loss = epoch_loss / len(train_loader.dataset)

        model.eval()
        with torch.no_grad():
            val_logits = model(X_val_t)
            val_loss = criterion(val_logits, y_val_t).item()
            val_preds = val_logits.argmax(dim=1)
            val_acc = (val_preds == y_val_t).float().mean().item()

        scheduler.step(val_acc)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_count = 0
        else:
            patience_count += 1
            if patience_count >= patience:
                print(f"    Early stopping at epoch {epoch}")
                break

        if epoch % 20 == 0 or epoch == 1:
            print(f"    Epoch {epoch:03d} | Train loss {train_loss:.4f} | "
                  f"Val loss {val_loss:.4f} | Val acc {val_acc:.3f}")

    model.load_state_dict(best_state)
    model.eval()

    with torch.no_grad():
        test_logits = model(X_test_t)
        y_test_pred = test_logits.argmax(dim=1).cpu().numpy()

    acc = accuracy_score(y_test, y_test_pred)
    report = classification_report(y_test, y_test_pred, target_names=le.classes_, digits=3)

    print(f"\n  DL Test Accuracy: {acc:.3f}")
    print(report)

    torch.save({
        "model_state_dict": model.state_dict(),
        "scaler": scaler,
        "feature_name": feature_name,
        "classes": le.classes_.tolist(),
    }, f"models/dl_salt_classifier_{feature_name.replace(' ', '_')}.pt")
    print(f"  Saved: models/dl_salt_classifier_{feature_name.replace(' ', '_')}.pt")

    return {
        "feature": feature_name,
        "accuracy": acc,
        "best_val_acc": best_val_acc,
        "report": report,
        "history": history,
        "scaler": scaler,
        "model_state": model.state_dict(),
    }


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 5: MODEL B — CONCENTRATION REGRESSOR
# ─────────────────────────────────────────────────────────────────────────────
#
#  This model answers: "Given this protein and the predicted salt type,
#  what concentration should I use?"
#
#  KEY DESIGN: The input is [ESM-2 embedding | salt type one-hot]
#  concatenated. This means the model KNOWS which salt was predicted
#  by Model A, and can learn different concentration ranges per salt.
#
#  For example, if Model A says "Ammonium Sulfate", Model B knows
#  to predict in the 1.0-3.0M range. If Model A says "NaCl",
#  Model B predicts in the 0.05-0.5M range.
#
#  We train on log-transformed concentrations because salt concentrations
#  are log-normally distributed — there are many values near 0.1-0.3M
#  and a long tail up to 3-4M. Log transform compresses this tail,
#  making the distribution more symmetric and easier to learn.
#
#  At inference, we reverse with expm1() to get back to Molar.
# ─────────────────────────────────────────────────────────────────────────────

def train_concentration_regressor(X_esm, y_conc, y_log, salt_labels, le):
    """
    Train concentration regressor with salt type as an additional feature.

    Args:
        X_esm:        ESM-2 embeddings, shape (n_samples, 320)
        y_conc:       Raw concentration in M
        y_log:        log(1 + concentration) — the actual training target
        salt_labels:  Array of salt type strings
        le:           LabelEncoder from Model A (for one-hot encoding)

    Returns:
        best_model:   Trained regressor (Ridge or XGBoost, whichever is better)
        reg_scaler:   StandardScaler fitted on training data
        reg_pca:      PCA fitted on training data
        metrics:      Dict with MAE, RMSE, R²
    """
    print("\n" + "=" * 60)
    print("SECTION 5: MODEL B — CONCENTRATION REGRESSOR")
    print("=" * 60)

    # ── 5a. Create one-hot encoding of salt type ──
    # This turns "Sodium Chloride" → [1, 0, 0, 0, ...]
    # and "Ammonium Sulfate" → [0, 1, 0, 0, ...]
    salt_encoded = le.transform(salt_labels)
    n_classes = len(le.classes_)
    salt_onehot = np.zeros((len(salt_encoded), n_classes))
    salt_onehot[np.arange(len(salt_encoded)), salt_encoded] = 1

    # ── 5b. Concatenate embedding + salt one-hot ──
    # Final feature vector = [320 ESM-2 dims | N salt type dims]
    X_combined = np.hstack([X_esm, salt_onehot])
    print(f"  Feature matrix: {X_combined.shape} "
          f"({X_esm.shape[1]} ESM-2 + {n_classes} salt one-hot)")

    # Training target is log-transformed concentration
    y = y_log

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_combined, y, test_size=0.2, random_state=SEED
    )
    # We also need raw concentrations for the test set (for reporting MAE in M)
    _, y_test_raw = train_test_split(y_conc, test_size=0.2, random_state=SEED)
    _, salt_test = train_test_split(salt_labels, test_size=0.2, random_state=SEED)

    # Standardize
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # PCA
    n_comp = min(60, X_combined.shape[1], len(X_train) // 10)
    pca = PCA(n_components=n_comp, random_state=SEED)
    X_train_p = pca.fit_transform(X_train_s)
    X_test_p = pca.transform(X_test_s)
    print(f"  PCA: {X_combined.shape[1]} → {n_comp} "
          f"({pca.explained_variance_ratio_.sum():.1%} variance)")

    # ── 5c. Train Ridge (linear baseline) ──
    # Ridge regression is a linear model with L2 regularization.
    # It almost never overfits, so it gives us a floor:
    # "If XGBoost can't beat Ridge, XGBoost is just memorizing."
    ridge = Ridge(alpha=10.0)
    ridge.fit(X_train_p, y_train)
    y_pred_ridge_log = ridge.predict(X_test_p)
    y_pred_ridge = np.expm1(y_pred_ridge_log)  # convert back from log scale
    mae_ridge = mean_absolute_error(y_test_raw, y_pred_ridge)
    rmse_ridge = np.sqrt(mean_squared_error(y_test_raw, y_pred_ridge))
    r2_ridge = r2_score(y_test_raw, y_pred_ridge)
    print(f"\n  Ridge:   MAE={mae_ridge:.4f} M | RMSE={rmse_ridge:.4f} M | R²={r2_ridge:.4f}")

    # ── 5d. Train XGBoost (regularized) ──
    xgb_model = xgb.XGBRegressor(
        n_estimators=300,
        max_depth=3,              # shallow trees — less overfitting
        learning_rate=0.03,       # slow learning rate
        subsample=0.7,            # use 70% of data per tree
        colsample_bytree=0.6,
        reg_alpha=1.0,            # strong L1 regularization
        reg_lambda=5.0,           # strong L2 regularization
        min_child_weight=10,      # require more samples per leaf
        gamma=0.5,                # minimum loss reduction to make a split
        random_state=SEED,
        n_jobs=-1,
        early_stopping_rounds=20,
    )
    xgb_model.fit(X_train_p, y_train,
                   eval_set=[(X_test_p, y_test)], verbose=False)
    y_pred_xgb_log = xgb_model.predict(X_test_p)
    y_pred_xgb = np.expm1(y_pred_xgb_log)
    mae_xgb = mean_absolute_error(y_test_raw, y_pred_xgb)
    rmse_xgb = np.sqrt(mean_squared_error(y_test_raw, y_pred_xgb))
    r2_xgb = r2_score(y_test_raw, y_pred_xgb)
    print(f"  XGBoost: MAE={mae_xgb:.4f} M | RMSE={rmse_xgb:.4f} M | R²={r2_xgb:.4f}")

    # ── 5e. Cross-validation on XGBoost ──
    X_all_p = pca.transform(scaler.transform(X_combined))
    cv_scores = cross_val_score(
        xgb.XGBRegressor(
            n_estimators=200, max_depth=3, learning_rate=0.03,
            subsample=0.7, colsample_bytree=0.6,
            reg_alpha=1.0, reg_lambda=5.0, min_child_weight=10,
            gamma=0.5, random_state=SEED, n_jobs=-1
        ),
        X_all_p, y, cv=5, scoring="neg_mean_absolute_error"
    )
    print(f"  XGBoost 5-Fold CV MAE (log scale): "
          f"{-cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

    # ── 5f. Pick best model ──
    if mae_xgb <= mae_ridge:
        best_model = xgb_model
        best_name = "XGBoost"
        y_pred_best = y_pred_xgb
        best_metrics = {"mae": mae_xgb, "rmse": rmse_xgb, "r2": r2_xgb}
    else:
        best_model = ridge
        best_name = "Ridge"
        y_pred_best = y_pred_ridge
        best_metrics = {"mae": mae_ridge, "rmse": rmse_ridge, "r2": r2_ridge}

    print(f"\n  Best regressor: {best_name} "
          f"(MAE={best_metrics['mae']:.4f} M)")

    # ── 5g. Per-salt-type MAE ──
    print(f"\n  Per-Salt-Type Performance:")
    per_salt = {}
    for salt in le.classes_:
        mask = salt_test == salt
        if mask.sum() >= 3:
            mae_s = mean_absolute_error(y_test_raw[mask], y_pred_best[mask])
            per_salt[salt] = {"mae": mae_s, "count": int(mask.sum())}
            print(f"    {salt:30s} | MAE: {mae_s:.4f} M | n={mask.sum()}")

    # ── PLOT: Predicted vs Actual ──
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].scatter(y_test_raw, y_pred_best, alpha=0.5, s=25,
                    c="#2E86AB", edgecolors="none")
    lims = [0, max(y_test_raw.max(), y_pred_best.max()) * 1.1]
    axes[0].plot(lims, lims, "r--", linewidth=2, label="Perfect prediction")
    axes[0].set_xlim(lims)
    axes[0].set_ylim(lims)
    axes[0].set_xlabel("Actual Concentration (M)", fontsize=12)
    axes[0].set_ylabel("Predicted Concentration (M)", fontsize=12)
    axes[0].set_title(f"Model B: Concentration Regressor ({best_name})\n"
                      f"MAE={best_metrics['mae']:.4f} M | R²={best_metrics['r2']:.4f}",
                      fontsize=13, fontweight="bold")
    textstr = (f"MAE  = {best_metrics['mae']:.4f} M\n"
               f"RMSE = {best_metrics['rmse']:.4f} M\n"
               f"R²   = {best_metrics['r2']:.4f}")
    props = dict(boxstyle="round,pad=0.5", facecolor="wheat", alpha=0.8)
    axes[0].text(0.05, 0.95, textstr, transform=axes[0].transAxes,
                 fontsize=11, verticalalignment="top", bbox=props)
    axes[0].legend()

    residuals = y_test_raw - y_pred_best
    axes[1].hist(residuals, bins=30, color="#44BBA4", edgecolor="white", alpha=0.85)
    axes[1].axvline(0, color="red", linestyle="--", linewidth=2)
    axes[1].axvline(np.mean(residuals), color="#F18F01", linestyle="--",
                    label=f"Mean error = {np.mean(residuals):.4f} M")
    axes[1].set_xlabel("Residual (Actual − Predicted) in M", fontsize=12)
    axes[1].set_ylabel("Count", fontsize=12)
    axes[1].set_title("Error Distribution", fontsize=13, fontweight="bold")
    axes[1].legend()

    plt.tight_layout()
    plt.savefig("plots_final/03_concentration_regressor.png",
                dpi=200, bbox_inches="tight")
    plt.close()
    print("  Saved: plots_final/03_concentration_regressor.png")

    # ── PLOT: Per-salt-type MAE ──
    if per_salt:
        fig, ax = plt.subplots(figsize=(10, max(4, len(per_salt) * 0.7)))
        names = list(per_salt.keys())
        maes = [per_salt[n]["mae"] for n in names]
        counts = [per_salt[n]["count"] for n in names]
        bars = ax.barh(names, maes, color="#2E86AB", edgecolor="white", height=0.6)
        ax.set_xlabel("MAE (M) — lower is better", fontsize=12)
        ax.set_title("Concentration Prediction Error by Salt Type",
                     fontsize=13, fontweight="bold")
        for bar, val, cnt in zip(bars, maes, counts):
            ax.text(bar.get_width() + 0.005,
                    bar.get_y() + bar.get_height() / 2,
                    f"{val:.4f} M (n={cnt})", va="center", fontsize=10)
        plt.tight_layout()
        plt.savefig("plots_final/04_per_salt_mae.png",
                    dpi=200, bbox_inches="tight")
        plt.close()
        print("  Saved: plots_final/04_per_salt_mae.png")

    # ── Save model artifacts ──
    joblib.dump(best_model, "models/concentration_regressor.joblib")
    joblib.dump(scaler, "models/regressor_scaler.joblib")
    joblib.dump(pca, "models/regressor_pca.joblib")
    print("  Saved model artifacts to models/")

    return best_model, scaler, pca, best_metrics, per_salt


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 6: COMPARISON PLOTS (Hand-Crafted vs ESM-2)
# ─────────────────────────────────────────────────────────────────────────────
#
#  This generates the "money slide" for your presentation:
#  a side-by-side comparison proving ESM-2 features outperform
#  hand-crafted features.
# ─────────────────────────────────────────────────────────────────────────────

def compare_features(X_hc, X_esm, y_conc, y_log, salt_labels, le):
    """
    Train the SAME model (XGBoost regressor) on hand-crafted features
    vs ESM-2 features to show the improvement from using a protein
    language model.
    """
    print("\n" + "=" * 60)
    print("SECTION 6: FEATURE COMPARISON (Hand-Crafted vs ESM-2)")
    print("=" * 60)

    # Prepare one-hot salt encoding
    salt_enc = le.transform(salt_labels)
    n_classes = len(le.classes_)
    salt_onehot = np.zeros((len(salt_enc), n_classes))
    salt_onehot[np.arange(len(salt_enc)), salt_enc] = 1

    results = {}

    for name, X_feat in [("Hand-Crafted", X_hc), ("ESM-2", X_esm)]:
        X = np.hstack([X_feat, salt_onehot])

        X_train, X_test, y_train, y_test = train_test_split(
            X, y_log, test_size=0.2, random_state=SEED
        )
        _, y_test_raw = train_test_split(y_conc, test_size=0.2, random_state=SEED)

        scaler = StandardScaler()
        X_tr = scaler.fit_transform(X_train)
        X_te = scaler.transform(X_test)

        n_comp = min(50, X.shape[1], len(X_train) // 10)
        pca_tmp = PCA(n_components=n_comp, random_state=SEED)
        X_tr = pca_tmp.fit_transform(X_tr)
        X_te = pca_tmp.transform(X_te)

        model = xgb.XGBRegressor(
            n_estimators=200, max_depth=3, learning_rate=0.03,
            subsample=0.7, colsample_bytree=0.6,
            reg_alpha=1.0, reg_lambda=5.0, min_child_weight=10,
            random_state=SEED, n_jobs=-1
        )
        model.fit(X_tr, y_train)
        y_pred = np.expm1(model.predict(X_te))
        mae = mean_absolute_error(y_test_raw, y_pred)
        r2 = r2_score(y_test_raw, y_pred)
        results[name] = {"mae": mae, "r2": r2, "y_true": y_test_raw, "y_pred": y_pred}
        print(f"  {name:15s} → MAE: {mae:.4f} M | R²: {r2:.4f}")

    # ── PLOT: Side-by-side comparison ──
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # MAE comparison
    names = list(results.keys())
    maes = [results[n]["mae"] for n in names]
    colors = ["#E84855", "#2E86AB"]
    bars = axes[0].bar(names, maes, color=colors, edgecolor="white", width=0.5)
    axes[0].set_ylabel("MAE (M) — lower is better", fontsize=12)
    axes[0].set_title("Mean Absolute Error", fontsize=13, fontweight="bold")
    for bar, val in zip(bars, maes):
        axes[0].text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
                     f"{val:.4f}", ha="center", fontsize=11, fontweight="bold")

    # R² comparison
    r2s = [results[n]["r2"] for n in names]
    bars = axes[1].bar(names, r2s, color=colors, edgecolor="white", width=0.5)
    axes[1].set_ylabel("R² — higher is better", fontsize=12)
    axes[1].set_title("R² Score", fontsize=13, fontweight="bold")
    axes[1].axhline(0, color="gray", linestyle="--", alpha=0.3)
    for bar, val in zip(bars, r2s):
        axes[1].text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
                     f"{val:.4f}", ha="center", fontsize=11, fontweight="bold")

    # Pred vs actual for both
    for i, (name, color) in enumerate(zip(names, colors)):
        d = results[name]
        axes[2].scatter(d["y_true"], d["y_pred"], alpha=0.4, s=15,
                        c=color, label=name, edgecolors="none")
    lim_max = max(y_conc.max(), max(results[n]["y_pred"].max() for n in names)) * 1.1
    axes[2].plot([0, lim_max], [0, lim_max], "k--", linewidth=1, alpha=0.5)
    axes[2].set_xlabel("Actual (M)", fontsize=12)
    axes[2].set_ylabel("Predicted (M)", fontsize=12)
    axes[2].set_title("Predictions Overlay", fontsize=13, fontweight="bold")
    axes[2].legend()

    plt.suptitle("Hand-Crafted Features vs ESM-2 Embeddings",
                 fontsize=15, fontweight="bold", y=1.02)
    plt.tight_layout()
    plt.savefig("plots_final/05_feature_comparison.png",
                dpi=200, bbox_inches="tight")
    plt.close()
    print("  Saved: plots_final/05_feature_comparison.png")

    return results


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 7: t-SNE VISUALIZATION
# ─────────────────────────────────────────────────────────────────────────────
#
#  t-SNE projects the 320-dim ESM-2 embeddings into 2D for visualization.
#  If proteins that crystallize with similar salts cluster together in the
#  t-SNE plot, that means ESM-2 embeddings ARE capturing information
#  relevant to crystallization — which validates our entire approach.
#
#  This is a powerful presentation slide.
# ─────────────────────────────────────────────────────────────────────────────

def plot_tsne(X_esm, y_conc, salt_labels):
    """Generate t-SNE plots colored by concentration and by salt type."""
    from sklearn.manifold import TSNE

    print("\n" + "=" * 60)
    print("SECTION 7: t-SNE VISUALIZATION")
    print("=" * 60)

    n = min(1500, len(X_esm))
    idx = np.random.choice(len(X_esm), n, replace=False)

    print(f"  Running t-SNE on {n} samples (this takes ~1 min)...")
    tsne = TSNE(n_components=2, perplexity=30, random_state=SEED, max_iter=1000)
    X_2d = tsne.fit_transform(X_esm[idx])

    fig, axes = plt.subplots(1, 2, figsize=(16, 7))

    # Colored by concentration
    sc1 = axes[0].scatter(X_2d[:, 0], X_2d[:, 1], c=y_conc[idx],
                          cmap="viridis", s=12, alpha=0.7, edgecolors="none")
    plt.colorbar(sc1, ax=axes[0], label="Salt Concentration (M)")
    axes[0].set_title("Colored by concentration", fontsize=13, fontweight="bold")
    axes[0].set_xlabel("t-SNE 1")
    axes[0].set_ylabel("t-SNE 2")

    # Colored by salt type
    unique_salts = list(set(salt_labels[idx]))
    color_map = plt.cm.Set2(np.linspace(0, 1, len(unique_salts)))
    salt_to_color = dict(zip(unique_salts, color_map))
    colors = [salt_to_color[s] for s in salt_labels[idx]]
    axes[1].scatter(X_2d[:, 0], X_2d[:, 1], c=colors,
                    s=12, alpha=0.7, edgecolors="none")
    # Legend
    for salt, color in salt_to_color.items():
        axes[1].scatter([], [], c=[color], label=salt, s=30)
    axes[1].legend(fontsize=8, loc="best", framealpha=0.8)
    axes[1].set_title("Colored by salt type", fontsize=13, fontweight="bold")
    axes[1].set_xlabel("t-SNE 1")
    axes[1].set_ylabel("t-SNE 2")

    plt.suptitle("t-SNE of ESM-2 Protein Embeddings",
                 fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.savefig("plots_final/06_tsne.png", dpi=200, bbox_inches="tight")
    plt.close()
    print("  Saved: plots_final/06_tsne.png")


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 8: DATA DISTRIBUTION PLOT
# ─────────────────────────────────────────────────────────────────────────────

def plot_data_overview(df):
    """
    Presentation slide: show the dataset distribution.
    Left:  Histogram of concentration per salt type (stacked)
    Right: Sample count per salt type
    """
    print("\n  Generating data overview plot...")

    fig, axes = plt.subplots(1, 2, figsize=(15, 5.5))

    # Histogram per salt type
    salts = df["salt_display"].unique()
    colors = plt.cm.Set2(np.linspace(0, 1, len(salts)))
    for salt, color in zip(salts, colors):
        sub = df[df["salt_display"] == salt]
        axes[0].hist(sub["salt_concentration_M"], bins=25, alpha=0.6,
                     label=salt, color=color, edgecolor="white")
    axes[0].set_xlabel("Salt Concentration (M)", fontsize=12)
    axes[0].set_ylabel("Count", fontsize=12)
    axes[0].set_title("Concentration Distribution by Salt Type",
                      fontsize=13, fontweight="bold")
    axes[0].legend(fontsize=8)

    # Sample count bar chart
    counts = df["salt_display"].value_counts()
    bars = axes[1].barh(counts.index, counts.values, color="#2E86AB",
                        edgecolor="white", height=0.6)
    axes[1].set_xlabel("Number of Samples", fontsize=12)
    axes[1].set_title("Samples per Salt Type", fontsize=13, fontweight="bold")
    for bar, val in zip(bars, counts.values):
        axes[1].text(bar.get_width() + 2, bar.get_y() + bar.get_height() / 2,
                     str(val), va="center", fontsize=10)

    plt.tight_layout()
    plt.savefig("plots_final/00_data_overview.png", dpi=200, bbox_inches="tight")
    plt.close()
    print("  Saved: plots_final/00_data_overview.png")


# ─────────────────────────────────────────────────────────────────────────────
#  SECTION 9: SAVE INFERENCE CONFIG
# ─────────────────────────────────────────────────────────────────────────────

def save_config(esm_model_name, le):
    """
    Save a JSON config file listing all the model files and settings.
    When you later build the Streamlit app, it reads this config
    to know which files to load.
    """
    config = {
        "esm_model": esm_model_name,
        "salt_classes": le.classes_.tolist(),
        "max_seq_length": 1022,
        "files": {
            "salt_classifier": "models/salt_classifier.joblib",
            "classifier_scaler": "models/classifier_scaler.joblib",
            "classifier_pca": "models/classifier_pca.joblib",
            "label_encoder": "models/label_encoder.joblib",
            "dl_salt_classifier": "models/dl_salt_classifier_DL_Combined.pt",
            "concentration_regressor": "models/concentration_regressor.joblib",
            "regressor_scaler": "models/regressor_scaler.joblib",
            "regressor_pca": "models/regressor_pca.joblib",
        }
    }
    with open("models/config.json", "w") as f:
        json.dump(config, f, indent=2)
    print("\n  Saved: models/config.json")


# ═════════════════════════════════════════════════════════════════════════════
#  MAIN: RUN EVERYTHING
# ═════════════════════════════════════════════════════════════════════════════

def main():
    ESM_MODEL = "facebook/esm2_t6_8M_UR50D"

    # ── 1. Clean data ──
    df = clean_dataset("crystallization_dataset.csv", min_salt_count=15)

    if len(df) < 50:
        print("\nFATAL: Too few samples after cleaning. "
              "Increase max_search in 01_data_collection.py and re-run.")
        return

    sequences = df["sequence"].tolist()
    y_conc = df["salt_concentration_M"].values
    y_log = df["log_salt"].values
    salt_labels = df["salt_display"].values

    # ── 2. Data overview plot ──
    plot_data_overview(df)

    # ── 3. Extract ESM-2 embeddings ──
    X_esm = extract_esm2_embeddings(sequences, model_name=ESM_MODEL, batch_size=8)

    # ── 4. Extract hand-crafted features (for comparison) ──
    X_hc, hc_names = extract_handcrafted(sequences)

    # ── 5. Train Model A: Salt Type Classifier ──
    le = LabelEncoder()
    y_enc = le.fit_transform(salt_labels)

    feature_sets = [
        ("Hand-Crafted", X_hc),
        ("ESM-2", X_esm),
        ("Combined", np.hstack([X_esm, X_hc]))
    ]

    classifier_results = {}
    for feature_name, X in feature_sets:
        clf, clf_scaler, clf_pca, metrics, all_results = train_salt_classifier(
            X, y_enc, le, feature_name=feature_name
        )
        classifier_results[feature_name] = {
            "clf": clf,
            "scaler": clf_scaler,
            "pca": clf_pca,
            "metrics": metrics,
            "all_results": all_results,
        }

    best_feature = max(
        classifier_results,
        key=lambda name: classifier_results[name]["metrics"]["cv_accuracy"]
    )
    best_clf_info = classifier_results[best_feature]
    print(f"\nBest overall Model A: {best_feature} features "
          f"(best inner model: {best_clf_info['metrics']['best_model']})")

    joblib.dump(best_clf_info["clf"], "models/salt_classifier.joblib")
    joblib.dump(best_clf_info["scaler"], "models/classifier_scaler.joblib")
    joblib.dump(best_clf_info["pca"], "models/classifier_pca.joblib")
    joblib.dump(le, "models/label_encoder.joblib")
    print("  Saved best salt classifier artifacts to models/")

    # ── 5b. Train DL classifier on combined features ──
    dl_results = train_dl_classifier(np.hstack([X_esm, X_hc]), y_enc, le,
                                     feature_name="DL Combined")

    # ── 6. Train Model B: Concentration Regressor ──
    reg, reg_scaler, reg_pca, reg_metrics, per_salt = \
        train_concentration_regressor(X_esm, y_conc, y_log, salt_labels, le)

    # ── 7. Feature comparison (the money slide) ──
    feat_results = compare_features(X_hc, X_esm, y_conc, y_log, salt_labels, le)

    # ── 8. t-SNE visualization ──
    plot_tsne(X_esm, y_conc, salt_labels)

    # ── 9. Save config ──
    save_config(ESM_MODEL, le)

    # ══════════════════════════════════════════════════════════════════════
    #  FINAL SUMMARY
    # ══════════════════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("TRAINING COMPLETE")
    print("=" * 60)

    print(f"\n  Dataset: {len(df)} samples, {df['salt_display'].nunique()} salt types")

    print(f"\n  MODEL A — Salt Type Classifier Results:")
    for feature_name, info in classifier_results.items():
        print(f"    {feature_name:10s} → Best model: {info['metrics']['best_model']:12s} | "
              f"Test Acc: {info['metrics']['accuracy']:.1%} | "
              f"CV Acc: {info['metrics']['cv_accuracy']:.1%}")

    print(f"\n  Best overall classifier: {best_feature} features "
          f"({best_clf_info['metrics']['best_model']})")

    print(f"\n  MODEL B — Concentration Regressor:")
    print(f"    MAE:  {reg_metrics['mae']:.4f} M")
    print(f"    RMSE: {reg_metrics['rmse']:.4f} M")
    print(f"    R²:   {reg_metrics['r2']:.4f}")

    print(f"\n  MODEL A — Deep Learning Classifier:")
    print(f"    Feature set: {dl_results['feature']}")
    print(f"    Test Accuracy: {dl_results['accuracy']:.1%}")
    print(f"    Best validation accuracy: {dl_results['best_val_acc']:.1%}")

    if feat_results:
        print(f"\n  FEATURE COMPARISON:")
        for name, r in feat_results.items():
            print(f"    {name:15s} → MAE: {r['mae']:.4f} M | R²: {r['r2']:.4f}")

    print(f"\n  SAVED FILES:")
    print(f"    models/          — all model artifacts (7 files + config.json)")
    print(f"    plots_final/     — all presentation plots (7 files)")

    print(f"\n  PLOTS GENERATED:")
    print(f"    00_data_overview.png           — dataset distribution")
    print(f"    01_salt_classifier_confusion.png — confusion matrix")
    print(f"    02_per_class_accuracy.png      — accuracy per salt type")
    print(f"    03_concentration_regressor.png  — pred vs actual + residuals")
    print(f"    04_per_salt_mae.png            — MAE breakdown by salt")
    print(f"    05_feature_comparison.png      — Hand-Crafted vs ESM-2")
    print(f"    06_tsne.png                    — embedding visualization")


if __name__ == "__main__":
    main()